import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export async function generateTransactionPDF(data: any, fromDate: string, toDate: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // 1. Header & Title
  doc.setFontSize(22);
  doc.setTextColor(16, 185, 129); // Emerald color
  doc.text("FULBARI RESTORA", pageWidth / 2, 20, { align: "center" });

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text("OFFICIAL TRANSACTION REPORT", pageWidth / 2, 28, { align: "center" });

  doc.line(20, 35, pageWidth - 20, 35);

  // 2. Report Metadata
  doc.setFontSize(10);
  doc.setTextColor(0);
  doc.text(`Report Period: ${fromDate} to ${toDate}`, 20, 45);
  doc.text(`Generation Date: ${new Date().toLocaleDateString('en-IN')}`, pageWidth - 20, 45, { align: "right" });

  // 3. Process Data for Table
  // Group by date
  const dailyData: Record<string, any> = {};
  
  data.transactions.forEach((tab: any) => {
    const dateStr = new Date(tab.closedAt || tab.openedAt).toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata' });
    const outletName = tab.Outlet.name.toUpperCase();
    const isCafe = outletName.includes("CAFE");
    const isChai = outletName.includes("CHAI");

    if (!dailyData[dateStr]) {
      dailyData[dateStr] = {
        cafeCash: 0, cafeUPI: 0,
        chaiCash: 0, chaiUPI: 0,
        total: 0
      };
    }

    const { paymentMode, totalAmount } = tab;
    
    if (isCafe) {
      if (paymentMode === "CASH") dailyData[dateStr].cafeCash += totalAmount;
      else if (paymentMode === "ONLINE" || paymentMode === "UPI") dailyData[dateStr].cafeUPI += totalAmount;
      else if (paymentMode === "SPLIT") {
        dailyData[dateStr].cafeCash += totalAmount / 2;
        dailyData[dateStr].cafeUPI += totalAmount / 2;
      }
    } else if (isChai) {
      if (paymentMode === "CASH") dailyData[dateStr].chaiCash += totalAmount;
      else if (paymentMode === "ONLINE" || paymentMode === "UPI") dailyData[dateStr].chaiUPI += totalAmount;
      else if (paymentMode === "SPLIT") {
        dailyData[dateStr].chaiCash += totalAmount / 2;
        dailyData[dateStr].chaiUPI += totalAmount / 2;
      }
    }
    
    dailyData[dateStr].total += totalAmount;
  });

  const tableRows = Object.entries(dailyData).map(([date, stats]: [string, any]) => [
    date,
    `Rs. ${stats.cafeCash.toFixed(0)}`,
    `Rs. ${stats.cafeUPI.toFixed(0)}`,
    `Rs. ${stats.chaiCash.toFixed(0)}`,
    `Rs. ${stats.chaiUPI.toFixed(0)}`,
    `Rs. ${stats.total.toFixed(0)}`
  ]);

  // 4. Main Table
  autoTable(doc, {
    startY: 55,
    head: [
      ["Date", "Cafe (Cash)", "Cafe (UPI)", "Chai (Cash)", "Chai (UPI)", "Daily Total"]
    ],
    body: tableRows,
    headStyles: { 
      fillColor: [16, 185, 129], 
      textColor: [255, 255, 255],
      fontSize: 10,
      fontStyle: 'bold'
    },
    styles: { 
      fontSize: 9,
      cellPadding: 4,
      valign: 'middle'
    },
    alternateRowStyles: { 
      fillColor: [240, 253, 244] 
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 25 },
      5: { fontStyle: 'bold', halign: 'right' }
    }
  });

  // 5. Final Grand Totals Section
  const grandTotal = data.transactions.reduce((sum: number, t: any) => sum + t.totalAmount, 0);
  const totalCash = data.transactions.filter((t:any) => t.paymentMode === "CASH").reduce((s:number, t:any) => s+t.totalAmount, 0);
  const totalUPI = data.transactions.filter((t:any) => t.paymentMode === "ONLINE" || t.paymentMode === "UPI").reduce((s:number, t:any) => s+t.totalAmount, 0);

  const finalY = (doc as any).lastAutoTable.finalY + 20;

  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("COLLECTION SUMMARY", 20, finalY);

  doc.setDrawColor(200);
  doc.line(20, finalY + 2, 80, finalY + 2);

  doc.setFontSize(10);
  doc.text(`Total Cash Collected: Rs. ${totalCash.toFixed(2)}`, 20, finalY + 12);
  doc.text(`Total UPI Collected: Rs. ${totalUPI.toFixed(2)}`, 20, finalY + 20);
  
  doc.setFontSize(14);
  doc.setTextColor(16, 185, 129);
  doc.text(`GRAND INCOME: Rs. ${grandTotal.toFixed(2)}`, 20, finalY + 32);

  // Footer for signature
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Report generated by Fulbari Operations Unit", 20, doc.internal.pageSize.height - 15);
  doc.text("Official Use Only", pageWidth - 20, doc.internal.pageSize.height - 15, { align: "right" });

  // 6. Save PDF
  const filename = `Fulbari_Report_${fromDate}_to_${toDate}.pdf`;
  doc.save(filename);
}
